### ISSUE TITLE
chrash

### ISSUE THREAD

**Issue by Frank18000** [BrandonWill/GrepolisBot#7] opened 2016-04-27 08:25 UTC
the bot chrashes after start up. The Dos box comes up en then closes again
when i remove the savesthe bot runs again but after restart the same problem

**Comment by beaubeire** [comment] 2016-04-27 10:56
Zelfde probleem/Same problem

**Comment by BrandonWill** [comment] 2016-04-28 07:14
I haven't been able to reproduce this problem. I changed the way it loads/saves the farming save file, but I also wrote it in a way that the old settings wouldn't be affected. 

Downloading the current folder gives me this:

![image](https://cloud.githubusercontent.com/assets/949047/14877996/9e28038a-0cee-11e6-9044-dff67eae4b35.png)

Closing and reopening gives me these errors (which it should give because nothing was technically saved), but it still runs:

![image](https://cloud.githubusercontent.com/assets/949047/14878038/e443d2f4-0cee-11e6-98b8-525a6128efa4.png)


Right click the run.bat file and click edit. You should see:

![image](https://cloud.githubusercontent.com/assets/949047/14878072/1904e348-0cef-11e6-9559-f6e9dc54686b.png)

Add a pause below it, so it looks like:

![image](https://cloud.githubusercontent.com/assets/949047/14878084/337b804c-0cef-11e6-9027-3f2efd5aae89.png)

Save it and rerun the file. It should stay open now so you can see the error it gives if any.

**Comment by BrandonWill** [comment] 2016-04-28 08:47
Looks like I left out the check for older save files. Recent version should detect them and load them

**Comment by Frank18000** [comment] 2016-04-28 15:28
![image](https://cloud.githubusercontent.com/assets/16511894/14891340/95717de8-0d66-11e6-8ef2-ca06b04ee87e.png)

**Comment by Frank18000** [comment] 2016-04-28 15:29
![image](https://cloud.githubusercontent.com/assets/16511894/14891390/bded8582-0d66-11e6-8da2-7b1f48b4c3c4.png)

**Comment by Frank18000** [comment] 2016-04-28 15:45
i stil have the problem i deleted the save files en stil a crash. This is the dos box i get
![image](https://cloud.githubusercontent.com/assets/16511894/14891894/d7e45da6-0d68-11e6-9aac-01afcd7eef3b.png)

**Comment by BrandonWill** [comment] 2016-04-28 23:49
That bug is fixed in the newest version

**Closed by BrandonWill** 2016-04-28 23:49 UTC
