### ISSUE TITLE
Conquerer

### ISSUE THREAD

**Issue by MrDafisque** [BrandonWill/GrepolisBot#9] opened 2016-06-17 10:23 UTC
Hola,

I am facing the issue right now, that the bot thinks all my town are being conquered. So it skips all the towns.
Anyone else having this issue?

so far
Dafisque

**Comment by grepolisplayer** [comment] 2016-06-17 17:29
Yes, i have this problem since 3 days, before that it worked great.

to BrandonWill:

the bot reloads fine, the 1st time it farms every village however at the second time (after the update count is over and farms again) we get a Village has a conqeuror (in every village) loop.

Brandon could you please look into this and fix the error or even better, remove the code for skipping a town if it has a conqeuror or think it has? because if i try to overtake a enemy city it also skips the city that the colonization ship came from. 

& 1 last thing to ask (has no big priority) i use windows & Linux (Lubuntu) it both works, however on Lubunti i dont see the queue pics of buildings & troops in the queue list.

(the conqeuror error is both on linux & windows, just tested on second pc, also has the error)

**Comment by BrandonWill** [comment] 2016-06-17 17:56
Working on this now. The conqueror error should've been removed awhile back because it's for the units you've sent. I thought I removed it, but I guess I didn't.

I'm surprised that the loading of images is problematic on Linux/Mac. It uses the same method as loading files, and I haven't heard anyone complain about it that yet. I'll have an update out in the next hour or two to fix both of these issues

**Comment by grepolisplayer** [comment] 2016-06-17 18:07
@ linux the troop & buildings images ( .png) are visible in the map but not in the program.

1 more interesting thing (low priority) 

in Lubuntu, if i have the path X/X/desktop/grepolisbot-master (folder)
the problem is its save files saves out of the map onto desktop X/X/desktop/....... (...., all the saves) its not a problem for me, just wanted to let you know.

btw awesome fast response i was afraid you might answer weeks later like most people or not at all.

ps. mind skyping in the future? i have some small idea's for the bot

**Comment by BrandonWill** [comment] 2016-06-17 19:28
I'm working on fixing that as well. I mostly wrote the program for windows, and different OSs have different pathing.

I don't use Skype. You can message me on hangouts if you'd like. Figure I might as well create one, so it's githubgrepolisbot@gmail.com if anyone wants to add it

**Comment by BrandonWill** [comment] 2016-06-17 20:03
Both of these issues should be fixed!

**Closed by BrandonWill** 2016-06-17 20:03 UTC
